# Generated by Django 2.1.15 on 2021-05-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_auto_20210528_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstaBorrado', models.BooleanField(default=True)),
                ('Evento', models.CharField(max_length=500)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
